### PR TITLE
feature/BA-805

### PR DESCRIPTION
**Pull request by mark-a-wilson**
This feature to re-instate price labels on both SWU and CWU opportunity cards on the opportunities list page, as well as minor styling to the list page.

From what I can see, we never had a price label on SWU opportunity cards, but we did on CWU opportunity cards. It looks like they got removed in the midst of 
https://github.com/BCDevExchange/devex/commit/845d17747725caa87965e571dd4aae9acf8a383f#diff-b2c027c6cc734b030a93efd9786c76cd. This was probably due to miscommunication between me and Andrew.

### CODE REVIEW

**Comment by scchapma** [comment]
Existing functionality broke during fix for BA-346.

**Comment by mark-a-wilson** [comment]
sure, shall I just make a single commit to develop to reinstate the labels?

**Comment by scchapma** [comment]
Yes, let's do that.

**Comment by mark-a-wilson** [comment]
@scchapma – OK, I've made [a single commit](
https://github.com/BCDevExchange/devex/commit/03c18532f4a6e795595f5d5be611ab3f9cb07b10)  to **develop** to do that.

I'll close this PR, but not delete feature/BA-805 yet – I'll try to rebase later for future consideration of redesign of opportunities list page.

✌️

**Pull request closed without merging**
