### PR TITLE
BA-1106 - Remove roadmap from application footer

### PR DESCRIPTION
**Pull request by mark-a-wilson**
improvement(core)

Removing stale Roadmap content, and using this as a first trial to update all related functional test files at the same time.

@crochcunill - can you please review the commits in this branch and comment whether I've missed anything, deleted anything that I should have left, or better ways to organize these commits for better clarity?

Fixes BA-1106.

### CODE REVIEW

**Comment by crochcunill** [comment]
Hi Mark, 

It seems that I had your email address after all!



Here is the file I promised to you. Copy it, change the extension to .zip and uncompress the file, then click on index,html.

I have removed any reference to Roadmap in the tests, so all clear!


Carles

**Comment by mark-a-wilson** [comment]
@SteveChapmanBCDX - Carles sent me a report of running this branch through his functional tests—everything passed. Can you please review and merge?

**Comment by sutherlanda** [comment]
@mark-a-wilson, can you please file a Jira ticket for this, and reference it in your commits and your PR?  Thanks.

**Comment by mark-a-wilson** [comment]
Jira ticket created: [BA-1106](https://bcdevex.atlassian.net/browse/BA-1106)

**Pull request merged**
